# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Adopt a JSR Br
email: adoptajsrbr@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Adopt a JSR Br Blog é uma iniciativa do SouJava que tem como principal objetivo
  ajudar na divulgação da tecnologia Java no Brasil.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: adoptajsrbr
github_username:  adoptajsrbr

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
